error: Flush stderr/out before aborting
A xemu user on Windows reported a mystery close after configuring their
required files. Nothing useful was displayed in the xemu.log file, and
running via cmd.exe also produced nothing interesting.

After failing, they were asked to run `echo %errorlevel%` which did result
in interesting output.

This change defensively flushes output streams and adds some newlines before
aborting or exiting due to a qemu error.